### ISSUE TITLE
Usability in C# WinUI 3 project

### ISSUE THREAD

**Issue by nono3551** [asklar/WinAppSDK-MediaPlayer#1]
Hi, is it possible to use this MediaPlayerElement inside WinUI 3 C# application? I can not find any example how to make work any c++ Control inside C#. I tried creating WinUI 3 component with Control but I had not luck referencing it from C# project.

**Comment by MuleaneEve** [comment]
Hi,

There is now a NuGet package that should work in your scenario:

https://www.nuget.org/packages/KlearTouch.MediaPlayer.WinUI/

You can find a [sample in its repo](https://github.com/KlearTouch/KlearTouch.MediaPlayer).

**Comment by nono3551** [comment]
> Hi,
> 
> There is now a NuGet package that should work in your scenario:
> 
> https://www.nuget.org/packages/KlearTouch.MediaPlayer.WinUI/
> 
> You can find a [sample in its repo](https://github.com/KlearTouch/KlearTouch.MediaPlayer).

Hi,

I need to use [MediaTimelineController](https://docs.microsoft.com/en-us/uwp/api/windows.media.mediatimelinecontroller?view=winrt-22000) which seem not available in [KlearTouch.MediaPlayer.WinUI](https://www.nuget.org/packages/KlearTouch.MediaPlayer.WinUI/).

**Comment by MuleaneEve** [comment]
It is available via:

```C#
MediaPlayerElement.UwpMediaPlayer.TimelineController
```

**Comment by nono3551** [comment]
@MuleaneEve thanks for information. I should also be able to include media player as WinRT componment which I could not recently because there was a bug in WinApp SDK. More information in this [isssue](https://github.com/microsoft/CsWinRT/issues/1148).
